name: Deploy App via snowcli

on:
  workflow_dispatch:
    inputs:
      snowflake_account:
        description: 'Snowflake Account'
        required: true
      snowflake_user:
        description: 'Snowflake User'
        required: true
      snowflake_password:
        description: 'Snowflake Password'
        required: true
      snowflake_role:
        description: 'Snowflake Role'
        required: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Snowflake Python Connector
        run: pip install snowflake-connector-python

      - name: Install yq
        run: sudo snap install yq

      - name: Set environment variables
        run: |
          export DATABASE=$(yq -e eval '.streamlit.database' snowflake.yml)
          export SCHEMA=$(yq -e eval '.streamlit.schema' snowflake.yml)
          echo "DATABASE=$DATABASE" >> $GITHUB_ENV
          echo "SCHEMA=$SCHEMA" >> $GITHUB_ENV

      - name: Create snowcli config
        env:
          SNOWFLAKE_ACCOUNT: ${{ github.event.inputs.snowflake_account }}
          SNOWFLAKE_USER: ${{ github.event.inputs.snowflake_user }}
          SNOWFLAKE_PASSWORD: ${{ github.event.inputs.snowflake_password }}
          SNOWFLAKE_ROLE: ${{ github.event.inputs.snowflake_role }}
        run: |
          mkdir -p ~/.snowflake
          cat << EOF > ~/.snowflake/config.toml
          [connections.default]
          account = "$SNOWFLAKE_ACCOUNT"
          user = "$SNOWFLAKE_USER"
          password = "$SNOWFLAKE_PASSWORD"
          connection_timeout = 600
          database = "$DATABASE"
          schema = "$SCHEMA"
          role = "$SNOWFLAKE_ROLE"
          EOF
          chmod 0600 ~/.snowflake/config.toml

      - name: Create Snowflake stage and upload files
        env:
          SNOWFLAKE_ACCOUNT: ${{ github.event.inputs.snowflake_account }}
          SNOWFLAKE_USER: ${{ github.event.inputs.snowflake_user }}
          SNOWFLAKE_PASSWORD: ${{ github.event.inputs.snowflake_password }}
          SNOWFLAKE_ROLE: ${{ github.event.inputs.snowflake_role }}
        run: |
          python - <<EOF
          import snowflake.connector
          import os

          # Connect to Snowflake
          ctx = snowflake.connector.connect(
              user=os.getenv('SNOWFLAKE_USER'),
              password=os.getenv('SNOWFLAKE_PASSWORD'),
              account=os.getenv('SNOWFLAKE_ACCOUNT'),
              role=os.getenv('SNOWFLAKE_ROLE'),
              database=os.getenv('DATABASE'),
              schema=os.getenv('SCHEMA')
          )
          cs = ctx.cursor()
          try:
              # Create stage if not exists
              cs.execute("CREATE STAGE IF NOT EXISTS my_app_stage;")
              
              # Upload files to stage
              files_to_upload = ["streamlit_app.py", "login_page.py", "data_edit_ui_page.py", "functions.py", "login_creds.csv", "table_dept_mapping.csv", "env_det.yml", "snowflake.yml", "requirements.txt"]
              for file in files_to_upload:
                  cs.execute(f"PUT file://{file} @my_app_stage AUTO_COMPRESS=TRUE;")
          finally:
              cs.close()
              ctx.close()
          EOF

      - name: Create app directory and copy all necessary files
        run: |
          mkdir -p ~/app
          cp -r . ~/app

      - name: Deploy the streamlit app
        shell: bash
        run: |
          cd ~/app
          snow streamlit deploy --debug --replace >> $GITHUB_STEP_SUMMARY
